language: python
sudo: false
cache: pip

python:
  - "3.6"

notifications:
  email: false

addons:
  postgresql: ${DB_VERSION}
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
